# =========================
# Coder Agent
# 多文件代码生成Agent
# =========================

from llm.deepseek import DeepSeekLLM
from llm.invocation import invoke_model, model_state_update

from prompts.coder_prompt import coder_prompt

from utils.code_extract import extract_code
from utils.file_roles import is_test_file_name

class CoderAgent:
    """
    Coder Agent核心处理类

    负责:
    1.读取File Planner任务
    2.调用DeepSeek生成C#代码
    3.保存多个代码文件
    4.返回结构化代码结果
    """


    def __init__(self, llm=None, generated_root="generated"):
        """
        初始化Coder Agent
        """

        self.llm = llm or DeepSeekLLM()
        self.generated_root = generated_root



    def run(self,state):
        """
        执行多文件代码生成

        Args:
            state:
                Agent共享状态

        Returns:
            更新后的状态
        """

        print("[Coder Agent]开始多文件生成")

        files = state.get(
            "files",
            []
        )

        if any(
            is_test_file_name(
                file_info.get("name", "") if isinstance(file_info, dict) else ""
            )
            for file_info in files
        ):
            raise ValueError(
                "test files must be generated by Test Generator, not Coder"
            )


        generated_files = []

        tool_records = []
        model_records = []


        for file_info in files:

            result = self.generate_file(
                state["query"],
                file_info,
                state,
            )


            generated_files.append(
                result["code"]
            )


            tool_records.append(
                result["tool"]
            )
            if result.get("model_record"):
                model_records.append(result["model_record"])


        return {

            "current_agent":
            "coder",


            "code":
            generated_files,

            "proposed_changes":
            generated_files,

            "proposal_source":
            "coder",


            "tools":
            state.get(
                "tools",
                []
            )
            +
            tool_records,


            "agent_history":
            state.get(
                "agent_history",
                []
            )
            +
            [
                "Coder Agent多文件生成完成"
            ],
            **model_state_update(state, model_records)

        }



    def generate_file(self,requirement,file_info,state=None):
        """
        根据文件规划生成单个文件

        Args:
            requirement:
                用户需求

            file_info:
                文件规划信息

        Returns:
            文件代码和工具记录
        """


        file_name = file_info[
            "name"
        ]


        description = file_info[
            "description"
        ]


        prompt = coder_prompt(
            f"""
需求:
{requirement}


请生成Unity C#文件。


文件名:
{file_name}


职责:
{description}


要求:
1.只输出C#代码
2.保持单一职责
3.符合Unity工程规范
""",
            (state or {}).get("unity_knowledge", {}),
        )


        invocation = invoke_model(
            self.llm,
            prompt,
            state or {},
            lambda content: (bool(extract_code(content).strip()), "non-empty C# code required"),
        )
        code = invocation.content


        code = extract_code(
            code
        )


        print(
            f"[Coder Agent]生成提案完成:{file_name}"
        )


        return {

            "code":
            {
                "file":
                file_name,

                "content":
                code
            },


            "tool":
            {
                "tool":
                "change_proposal",

                "path":
                "generated/" + file_name,

                "status":
                "pending"
            },

            "model_record": invocation.record

        }
